import Counter from './Counter'

export default function Content() {
    return (
        <div className="content">
            <h2>Content</h2>
            <Counter />
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Augue mauris augue neque gravida in. Erat velit scelerisque in dictum non. Aliquam ultrices sagittis orci a scelerisque. Donec enim diam vulputate ut pharetra sit amet. In dictum non consectetur a erat nam at lectus. Leo vel fringilla est ullamcorper eget nulla facilisi etiam. Elementum integer enim neque volutpat ac. Elit ut aliquam purus sit amet luctus venenatis lectus. Enim sed faucibus turpis in eu mi bibendum neque. Sit amet cursus sit amet dictum sit amet justo. Eu ultrices vitae auctor eu augue ut lectus arcu bibendum. Viverra suspendisse potenti nullam ac tortor vitae purus. Aliquam ultrices sagittis orci a scelerisque purus semper eget. Sollicitudin nibh sit amet commodo nulla. Bibendum enim facilisis gravida neque convallis a cras. Nunc scelerisque viverra mauris in aliquam sem fringilla ut morbi. Lectus sit amet est placerat in egestas erat imperdiet. Tellus at urna condimentum mattis pellentesque id nibh. Aliquam nulla facilisi cras fermentum odio eu feugiat.

Amet massa vitae tortor condimentum lacinia quis vel eros donec. Morbi tristique senectus et netus. Ultrices tincidunt arcu non sodales neque sodales ut etiam sit. Arcu vitae elementum curabitur vitae. Ac feugiat sed lectus vestibulum mattis ullamcorper velit sed ullamcorper. Ultrices dui sapien eget mi proin sed libero enim. Sed augue lacus viverra vitae congue eu consequat ac felis. Dolor magna eget est lorem ipsum dolor sit. Eu tincidunt tortor aliquam nulla facilisi cras fermentum. Aliquam sem et tortor consequat id. Lectus urna duis convallis convallis tellus id interdum. Mauris a diam maecenas sed enim ut sem viverra aliquet. Orci porta non pulvinar neque laoreet suspendisse interdum. Euismod in pellentesque massa placerat. Facilisi etiam dignissim diam quis enim. Lobortis feugiat vivamus at augue eget arcu.

Dapibus ultrices in iaculis nunc. Vulputate dignissim suspendisse in est ante in nibh mauris. Lorem donec massa sapien faucibus et molestie ac. Orci eu lobortis elementum nibh tellus molestie nunc non blandit. Amet consectetur adipiscing elit ut aliquam purus sit. Velit euismod in pellentesque massa placerat. Fusce ut placerat orci nulla pellentesque dignissim. Et malesuada fames ac turpis egestas integer eget aliquet nibh. Neque sodales ut etiam sit amet nisl. In pellentesque massa placerat duis ultricies lacus sed turpis tincidunt. Turpis egestas pretium aenean pharetra magna ac placerat. Cursus sit amet dictum sit.

Sagittis purus sit amet volutpat consequat mauris nunc congue nisi. Vel turpis nunc eget lorem dolor sed viverra ipsum nunc. Mauris ultrices eros in cursus turpis massa tincidunt. Fermentum iaculis eu non diam. Morbi tristique senectus et netus. Ullamcorper sit amet risus nullam. Sit amet consectetur adipiscing elit ut aliquam. Turpis massa tincidunt dui ut ornare lectus sit amet est. Arcu dictum varius duis at. Blandit massa enim nec dui nunc.

Sem et tortor consequat id porta. Venenatis a condimentum vitae sapien pellentesque habitant. Suspendisse sed nisi lacus sed viverra tellus in hac habitasse. Leo vel fringilla est ullamcorper eget nulla. Turpis massa tincidunt dui ut ornare lectus sit amet est. Nibh praesent tristique magna sit amet purus. Arcu dictum varius duis at consectetur lorem donec. Purus ut faucibus pulvinar elementum integer enim neque. Faucibus purus in massa tempor nec feugiat nisl pretium fusce. Aliquam etiam erat velit scelerisque in. Habitant morbi tristique senectus et netus et. Nisi lacus sed viverra tellus. Augue interdum velit euismod in pellentesque massa placerat duis. Quam adipiscing vitae proin sagittis nisl rhoncus mattis. Ut morbi tincidunt augue interdum velit euismod in pellentesque massa.

Sed ullamcorper morbi tincidunt ornare massa eget. Convallis tellus id interdum velit laoreet. Lacus viverra vitae congue eu consequat ac felis donec et. Nulla aliquet porttitor lacus luctus accumsan tortor posuere. Nibh sed pulvinar proin gravida hendrerit. In aliquam sem fringilla ut morbi tincidunt. Purus in massa tempor nec feugiat nisl pretium fusce id. Parturient montes nascetur ridiculus mus mauris. Ornare suspendisse sed nisi lacus sed viverra tellus. Cursus vitae congue mauris rhoncus aenean. A iaculis at erat pellentesque adipiscing commodo. Nunc vel risus commodo viverra maecenas. Nec dui nunc mattis enim ut tellus elementum sagittis.

Pharetra diam sit amet nisl. Tincidunt dui ut ornare lectus sit. Tristique magna sit amet purus gravida quis blandit turpis. Nulla malesuada pellentesque elit eget gravida. Pulvinar pellentesque habitant morbi tristique senectus et netus et. Placerat orci nulla pellentesque dignissim enim sit. Eget nunc scelerisque viverra mauris in aliquam sem fringilla ut. Accumsan in nisl nisi scelerisque eu ultrices vitae auctor. Urna porttitor rhoncus dolor purus non enim praesent elementum. Scelerisque eu ultrices vitae auctor eu augue ut lectus. Purus faucibus ornare suspendisse sed nisi lacus. Lectus quam id leo in vitae turpis massa sed. Volutpat diam ut venenatis tellus in metus. At varius vel pharetra vel turpis nunc eget. Pretium nibh ipsum consequat nisl. Ut tristique et egestas quis ipsum suspendisse ultrices gravida dictum.

Tellus molestie nunc non blandit massa enim nec dui nunc. Amet consectetur adipiscing elit pellentesque. Ipsum consequat nisl vel pretium lectus quam id. Quam quisque id diam vel quam elementum. Pulvinar neque laoreet suspendisse interdum consectetur libero id faucibus. Dignissim suspendisse in est ante in. Sed libero enim sed faucibus. Suscipit adipiscing bibendum est ultricies integer quis auctor. Egestas sed sed risus pretium quam. Orci phasellus egestas tellus rutrum tellus pellentesque eu tincidunt.</p>
        </div>
    )
}
